# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
        migrations.AddField(
            model_name='film',
            name='tags',
            field=models.ManyToManyField(to='films.Tag'),
        ),
    ]
