# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
